spring:
  profiles:
    active: development
  # Security configuration
  security:
    user:
      name: user
      password: user
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: order-service
    password: order-service
    driver-class-name: org.postgresql.Driver
  jpa:
    enabled: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: create
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mail:
    host: smtp.example.com
    port: 587
    username: username
    password: password

server:
  port: 8090

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG

